### ISSUE TITLE
Added dates for the month are misplaced

### ISSUE THREAD

**Issue by ToBeKraft** [glizzykingdreko/CalIntra#1]
Here is an image of how it looks:
<img width="160" alt="Screen Shot 2024-02-19 at 4 02 18 PM" src="https://github.com/glizzykingdreko/CalIntra/assets/108221059/a81be9cd-bc31-4cdf-bd70-e3992527354d">

Inspecting the code in the browser, didn't show any issue to me:
<img width="404" alt="Screen Shot 2024-02-19 at 4 06 16 PM" src="https://github.com/glizzykingdreko/CalIntra/assets/108221059/4035d9d8-077e-4b1f-a9eb-328f3c1e1a72">

I'm using
Chrome Version 121.0.6167.139 (Official Build) (x86_64)
Improved Intra 42 4.3.1
CalIntra 0.1.4

**Comment by glizzykingdreko** [comment]
Hi, the 42 School didn't accepted the features of this extension as native of their website and other than that I'm not a member of them anymore. So I can't help you in any way or check for the issue.
