### ISSUE TITLE
Just Nothing

### ISSUE THREAD

**Issue by Tsiangana** [glizzykingdreko/CalIntra#2]
good morning
I'm a new student at school 42 and I could see that they are much more advanced than me

Could you give me some advice on how to be a better programmer and succeed in 42

**Comment by glizzykingdreko** [comment]
Leave the school

**Comment by Tsiangana** [comment]
I passed the pool and I'm already an official cadet, I'm already in the middle of graphic projects and I'll probably finish communcore at the beginning of next year.

I don't want to be one of the best, I want to be the best, that's why I'm looking for 42 students who are already advanced to give me advice.

**Comment by glizzykingdreko** [comment]
Unless your dream is to study the basics of some programming language for years and years and then be sold as a product to one of their partner companies to earn the minimum wage in your country, as I told you leave school. 

In three years you will have acquired such basic skills that you will be forced to find a job through them.

Good luck.

**Comment by Tsiangana** [comment]
Thank you for your opinion, I don't intend to get a job, I just want to acquire skills to be able to carry out my personal projects, I want to create my own programming company. At the moment I'm not very good, but I want to be much better in order to achieve my goals.

I don't know if it would be unusual to ask, but have you already completed communcore and are you working as you should?

Why would you advise me to give up on school? Is it because your result doesn't match the expectations that the school presented?

**Comment by glizzykingdreko** [comment]
I repeat again: Once you complete their learning program you will have such a minimal level of knowledge that the only kind of projects or jobs you will be able to sustain are those assigned by them. 

Always remember that if you don't pay for a product you are the product.

**Comment by Tsiangana** [comment]
and you have already completed communcore
